root: true
ignorePatterns:
  - '*.config.*'
  - .yarn/*
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/strict'
  - 'plugin:@typescript-eslint/stylistic'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
env:
  shared-node-browser: true
  es2023: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: true
  ecmaVersion: 2023
  sourceType: module
plugins:
  - '@typescript-eslint'
  - import
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
      ecmaVersion: 2023
      project:
        - '**/tsconfig.json'
      projectFolderIgnoreList:
        - '**/node_modules/**'
    node: true
rules:
  max-len:
    - error
    - code: 120
  no-eval:
    - error
    - allowIndirect: true
  no-floating-decimal: error
  space-infix-ops: error
  new-cap:
    - error
    - capIsNewExceptionPattern: Mixin$
  brace-style:
    - error
    - stroustrup
    - allowSingleLine: true
  '@typescript-eslint/consistent-type-imports':
    - error
    - fixStyle: separate-type-imports
      prefer: type-imports
  indent:
    - error
    - 2
    - SwitchCase: 1
      VariableDeclarator: 1
      outerIIFEBody: 1
      MemberExpression: 1
      FunctionDeclaration:
        parameters: 1
        body: 1
      FunctionExpression:
        parameters: 1
        body: 1
      CallExpression:
        arguments: 1
      ArrayExpression: 1
      ObjectExpression: 1
      ImportDeclaration: 1
      flatTernaryExpressions: false
      ignoreComments: false
      ignoredNodes:
        - TemplateLiteral *
        - TSTypeParameterInstantiation
        - 'FunctionExpression > .params[decorators.length > 0]'
        - 'FunctionExpression > .params > :matches(Decorator, :not(:first-child))'
        - 'ClassBody.body > PropertyDefinition[decorators.length > 0] > .key'
  operator-linebreak:
    - error
    - after
    - overrides:
        '?': before
        ':': before
  import/no-unresolved: 'off'
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - - parent
          - sibling
          - index
        - object
        - unknown
        - type
      newlines-between: always
      warnOnUnassignedImports: true
      alphabetize:
        order: asc
        caseInsensitive: true
  '@typescript-eslint/no-empty-interface': 'off'
  '@typescript-eslint/prefer-string-starts-ends-with': 'off'
  '@typescript-eslint/no-dynamic-delete': 'off'
  '@typescript-eslint/no-non-null-assertion': 'off'
  '@typescript-eslint/member-ordering':
    - error
    - default:
        - signature
        - constructor
        - static-field
        - public-field
        - protected-field
        - private-field
        - field
        - public-method
        - static-method
        - protected-method
        - private-method
        - method
  no-throw-literal: 'off'
  require-jsdoc: 'off'
  valid-jsdoc: 'off'
  class-methods-use-this:
    - error
    - exceptMethods:
        - connectedCallback
        - disconnectedCallback
        - performUpdate
        - shouldUpdate
        - firstUpdated
        - update
        - updated
        - createRenderRoot
        - render
