semi: true
singleQuote: true
trailingComma: all
arrowParens: always
printWidth: 100
tabWidth: 2
useTabs: false
endOfLine: lf
quoteProps: as-needed
jsxSingleQuote: false
insertPragma: false
requirePragma: false
proseWrap: always
htmlWhitespaceSensitivity: ignore
overrides:
  - files: '*.json'
    options:
      parser: json
